server:
    port: 8180

spring:
    cloud:
        config:
            name: Spring Cloud Config Server
            label: master
            server:
                git:
#                    uri: https://github.com/spring-cloud-samples/config-repo
                    uri: https://gitlab.com/tuannt39/spring-cloud-config.git
                    username: demo
                    password: demo

#spring:
#    profiles:
#        active: native
#    cloud:
#        config:
#            name: Spring Cloud Config Server
#            server:
#                native:
#                    searchLocations: /home/teo/Downloads/study/spring-cloud-config
